=== StasVladyka1992/JWD23_03_02/src/resources/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.w3.org/menu"
        xmlns:tns="http://www.w3.org/menu"
        elementFormDefault="qualified"
        attributeFormDefault="qualified">

    <element name="menu" type="tns:Menu"/>
    <complexType name="Menu">
        <choice maxOccurs="unbounded">
            <element name="breakfast_menu" type="tns:BreakfastMenu"/>
            <element name="hot_snack_menu" type="tns:HotSnackMenu"/>
            <element name="cold_snack_menu" type="tns:ColdSnackMenu"/>
        </choice>
    </complexType>
    <element name="cold_snack_menu" type="tns:ColdSnackMenu"/>
    <complexType name="ColdSnackMenu">
        <!--In all you can use any sequence of elements but only ONCE!
        There is a solution -> use <choice> with maxOccurs="unbounded"-->
        <choice maxOccurs="unbounded">
            <element name="dish" type="tns:Dish" minOccurs="0"/>
        </choice>
    </complexType>
    <element name="hot_snack_menu" type="tns:HotSnackMenu"/>
    <complexType name="HotSnackMenu">
        <!--In all you can use any sequence of elements but only ONCE!
        There is a solution -> use <choice> with maxOccurs="unbounded"-->
        <choice maxOccurs="unbounded">
            <element name="dish" type="tns:Dish" minOccurs="0"/>
        </choice>
    </complexType>
    <element name="breakfast_menu" type="tns:BreakfastMenu"/>
    <complexType name="BreakfastMenu">
        <!--In all you can use any sequence of elements but only ONCE!
        There is a solution -> use <choice> with maxOccurs="unbounded"-->
        <choice maxOccurs="unbounded">
            <element name="dish" type="tns:Dish" minOccurs="0"/>
        </choice>
    </complexType>
    <!--Dish-->
    <complexType name="Dish">
        <sequence>
            <element name="photo" type="tns:Photo"/>
            <element name="name" type="tns:Name"/>
            <element name="description_price" type="tns:Description"/>
            <element name="portion" type="tns:Portion"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
        <attribute name="currency" type ="tns:Currency" use="required"/>
    </complexType>
    <!--Photo type-->
    <simpleType name="Photo">
        <restriction base="anyURI">
            <pattern value=".+\.(gif|jpg|png|bmp|psd|jpeg|tiff|pcx)"/>
        </restriction>
    </simpleType>
    <!--Name type-->
    <simpleType name="Name">
        <restriction base="token"></restriction>
    </simpleType>

    <!--Description type-->
    <complexType name="Description">
        <sequence>
            <element name="description" type="tns:DescriptionPrice" maxOccurs="3"/>
        </sequence>
        <attribute name="additionalInfo" type="string"/>
    </complexType>


    <!--DescriptionPrice-->
    <!--Логичнее было бы сделать значение description и price элементами. Т.к. они описываются свойсвта блюда
    Однако я решил сделать их именно атрибутами, так как:
     1) таким способом легче связать свойства "decription" и "price"
     2) не потребуется создавать новый тип данных, хранящий коллекцию объектов, имеющих поля "description" и "price"
    -->
    <complexType name="DescriptionPrice">
        <attribute name="description" type="token" use="required"/>
        <attribute name="price" type="positiveInteger"/>
    </complexType>

    <!--Portion type-->
    <simpleType name="Portion">
        <restriction base="string">
            <pattern value="(\d+ шт\.)|(\d+(/\d+)+)|(\d+)"/>
            <!--В xml регулярки ограничены:
             1) Символ ^ и $ не действуют. XML сама их неявно добавляет
             2) квантификаторы в явном виде не используются
            подробнее:
            http://qaru.site/questions/3383112/regular-expression-in-xml-schema-definition-fails-->
        </restriction>
    </simpleType>
    <!--Price type-->
    <!--Currency-->
    <simpleType name="Currency">
        <restriction base="string">
            <enumeration value="рос. руб."/>
            <enumeration value="дол. США"/>
            <enumeration value="eвро"/>
            <enumeration value="руб."/>
        </restriction>
    </simpleType>
</schema>

=== StasVladyka1992/JWD23_03_02/src/resources/menu.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xns:menu xmlns:xns="http://www.w3.org/menu"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.w3.org/menu  menu.xsd">
    <xns:cold_snack_menu>
        <!--TODO разобраться с элементом ID-->
        <xns:dish xns:id="solted_trout_salmon" xns:currency="руб.">
            <xns:photo>E:\Java\JWD23-task03\src\photo12.jpg</xns:photo>
            <xns:name>Ассорти рыбное</xns:name>
            <xns:description_price>
                <xns:description xns:description="Слабосоленая форель, семга"/>
            </xns:description_price>
            <xns:portion>100/20/50</xns:portion>
        </xns:dish>
        <!--<xns:dish xns:id="tartlets_with_red_caviar" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo13.jpg</xns:photo>-->
            <!--<xns:name>Тарталетки с красной икрой</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Тарталетки с красной икрой"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>60/50</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="russian_snack" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo14.jpg</xns:photo>-->
            <!--<xns:name>Закуска по-русски</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description-->
                        <!--xns:description="Кусочки атлантической сельди с отварным картофелем, луком, лимоном и зеленью"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>70/50/2/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="chicken_roll" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo15.jpg</xns:photo>-->
            <!--<xns:name>Куриный рулет</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Куриный рулет собственного производства"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>100/5</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="basturma" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo16.jpg</xns:photo>-->
            <!--<xns:name>Бастурма</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Вяленая вырезка из говяжьего мяса"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>50/5</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="assorted_meat" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo17.jpg</xns:photo>-->
            <!--<xns:name>Ассорти мясное</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Нарезка из буженины, бастурмы, куриного рулета собственного производства и колбасы"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>100/30</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="boiled_tongue" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo18.jpg</xns:photo>-->
            <!--<xns:name>Язык отварной</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Нарезка нежного говяжьего языка, подается с хреном"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>80/20/1</xns:portion>-->
        <!--</xns:dish>-->
        <xns:dish xns:id="assorted_eggplant" xns:currency="руб.">
            <xns:photo>E:\Java\JWD23-task03\src\photo19.jpg</xns:photo>
            <xns:name>Жареные баклажаны с помидорами</xns:name>
            <xns:description_price>
                <xns:description xns:description="1. c помидорами"/>
                <xns:description xns:description="2. c чесноком"/>
                <xns:description xns:description="3. c орехами"/>
            </xns:description_price>
            <xns:portion>100/5</xns:portion>
        </xns:dish>
        <!--<xns:dish xns:id="home_pickles" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo20.jpg</xns:photo>-->
            <!--<xns:name>Соленья по-домашнему</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Маринованные овощи"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>150/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="grandmother_treat" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo21.jpg</xns:photo>-->
            <!--<xns:name>Бабушкины угощения</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Ассорти из маринованных грибов"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>120/20/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="cheese_plate" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo22.jpg</xns:photo>-->
            <!--<xns:name>Сырная тарелка</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Сыр Чечел, дор блю, российский, мраморный"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>100/5</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="white_cheese" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo23.jpg</xns:photo>-->
            <!--<xns:name>Брынза</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Рассольный сыр, изготавливаемый из овечьего молока"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>75/5</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="green_stuff" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo24.jpg</xns:photo>-->
            <!--<xns:name>Зелень</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Кинза, лук, петрушка, укроп, базилик"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>30</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="assorted_vegatables" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo25.jpg</xns:photo>-->
            <!--<xns:name>Ассорти овощное</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Свежие помидоры, болгарский перец, огурцы, редис и зелень"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>150/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="vegetble_bouquet" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo26.jpg</xns:photo>-->
            <!--<xns:name>Овощной букет</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Корейская морковь, капуста, фунчоза"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>150/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="armenian_vegetables" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo27.jpg</xns:photo>-->
            <!--<xns:name>Овощи по армянски</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Мелко нарезанные свежие помидоры, огурцы, болгарский перец, укроп, базилик, кинза, лист салата, зелень"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>150/40</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="senior_tomato" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo28.jpg</xns:photo>-->
            <!--<xns:name>Сеньор Помидор</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description="Помидор, фаршированный сырным муссом"/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>150/1</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="side_dish_festival" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo29.jpg</xns:photo>-->
            <!--<xns:name>Фестиваль салатов</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description=""/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>400/10</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="olives" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo30.jpg</xns:photo>-->
            <!--<xns:name>Оливки, маслины</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description=""/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>50</xns:portion>-->
        <!--</xns:dish>-->
        <!--<xns:dish xns:id="lemon" xns:currency="руб.">-->
            <!--<xns:photo>E:\Java\JWD23-task03\src\photo31.jpg</xns:photo>-->
            <!--<xns:name>Лимон</xns:name>-->
            <!--<xns:description_price>-->
                <!--<xns:description xns:description=""/>-->
            <!--</xns:description_price>-->
            <!--<xns:portion>60</xns:portion>-->
        <!--</xns:dish>-->
        <xns:dish xns:id="matsoni" xns:currency="руб.">
            <xns:photo>E:\Java\JWD23-task03\src\photo32.jpg</xns:photo>
            <xns:name>Мацони</xns:name>
            <xns:description_price>
